### ISSUE TITLE
 > create table pages_pages ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'visible'

### ISSUE THREAD

**Issue by serhey-svintsitskiy** [execut/yii2-cms#1]
```
sergey@sergey-sayulinuxmint ~/www/yiicms.loc $ ./yii migrate/up --interactive 0
Yii Migration Tool (based on Yii v2.0.26)

Total 13 new migrations to be applied:
        kartik\dynagrid\migrations\m140101_100000_dynagrid
        execut\goods\migrations\m170214_065041_addArticlesTable
        execut\pages\migrations\m170401_190746_createBaseTable
        execut\menu\migrations\m170402_192559_initalStructure
        execut\settings\migrations\m170501_182316_initialStructure
        execut\menu\migrations\m170514_165149_addSortToItems
        execut\menu\migrations\m170829_010636_addMenuDefaultValue
        execut\seo\migrations\m170829_151236_addKeywordsToModules
        execut\files\migrations\m170830_223319_createBaseStructure
        execut\alias\migrations\m170917_152309_addLogsTable
        execut\goods\migrations\m180408_162536_addUrlsToGoods
        execut\settings\migrations\m180827_141237_changeValueFieldType
        execut\settings\migrations\m180828_142016_setValueNullable

*** applying kartik\dynagrid\migrations\m140101_100000_dynagrid
    > create table {{%dynagrid}} ... done (time: 0.221s)
    > add primary key dynagrid_PK on {{%dynagrid}} (id) ... done (time: 0.424s)
    > create table {{%dynagrid_dtl}} ... done (time: 0.259s)
    > add primary key dynagrid_dtl_PK on {{%dynagrid_dtl}} (id) ... done (time: 0.416s)
    > add foreign key dynagrid_FK1: {{%dynagrid}} (filter_id) references {{%dynagrid_dtl}} (id) ... done (time: 0.764s)
    > add foreign key dynagrid_FK2: {{%dynagrid}} (sort_id) references {{%dynagrid_dtl}} (id) ... done (time: 0.706s)
*** applied kartik\dynagrid\migrations\m140101_100000_dynagrid (time: 2.825s)

*** applying execut\goods\migrations\m170214_065041_addArticlesTable
    > create table goods_brands ... done (time: 0.275s)
    > create table goods_articles ... done (time: 0.224s)
    > add column goods_brand_id integer to table goods_articles ... done (time: 0.382s)
    > add foreign key goods_articles_goods_brand_id_fk: goods_articles (goods_brand_id) references goods_brands (id) ... done (time: 0.656s)
    > create unique index goods_articles_goods_articles_uk on goods_articles (goods_brand_id,article_filtered) ... done (time: 0.291s)
    > create index goods_articles_goods_brand_id_i on goods_articles (goods_brand_id) ... done (time: 0.157s)
    > create index goods_articles_article_i on goods_articles (article) ... done (time: 0.191s)
    > create index goods_articles_article_filtered_i on goods_articles (article_filtered) ... done (time: 0.191s)
    > create index goods_articles_visible_i on goods_articles (visible) ... done (time: 0.218s)
    > create table goods_goods ... done (time: 0.208s)
    > add column goods_article_id integer to table goods_goods ... done (time: 0.392s)
    > add foreign key goods_goods_goods_article_id_fk: goods_goods (goods_article_id) references goods_articles (id) ... done (time: 1.003s)
*** applied execut\goods\migrations\m170214_065041_addArticlesTable (time: 4.282s)

*** applying execut\pages\migrations\m170401_190746_createBaseTable
    > create table pages_pages ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'visible'
The SQL being executed was: CREATE TABLE `pages_pages` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `created` datetime(0) NOT NULL DEFAULT now(),
        `updated` datetime(0),
        `name` varchar(255) NOT NULL,
        `visible` tinyint(1) NOT NULL DEFAULT 'true'
) (/home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `p...')
#1 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('CREATE TABLE `p...')
#2 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 [internal function]: yii\db\Migration->createTable('pages_pages', Array)
#4 /home/sergey/www/yiicms.loc/vendor/execut/yii2-migration/Inverter.php(86): call_user_func_array(Array, Array)
#5 /home/sergey/www/yiicms.loc/vendor/execut/yii2-migration/Migration.php(41): execut\yii\migration\Inverter->up()
#6 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/db/Migration.php(114): execut\yii\migration\Migration->safeUp()
#7 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(724): yii\db\Migration->up()
#8 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(200): yii\console\controllers\BaseMigrateController->migrateUp('execut\\pages\\mi...')
#9 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#10 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#13 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#14 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#15 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#16 /home/sergey/www/yiicms.loc/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /home/sergey/www/yiicms.loc/yii(23): yii\base\Application->run()
#18 {main}
*** failed to apply execut\pages\migrations\m170401_190746_createBaseTable (time: 0.001s)


2 from 13 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

**Comment by execut** [comment]
Hello! Thanks for report. This is a bug with the component execut/yii2-migration and the database Mysql. I will fix it as time will be. Try Postgresql.

**Comment by execut** [comment]
Fixed errors in mysql
